### ISSUE TITLE
winsound module issue

### ISSUE THREAD

**Issue by rachyrachyrach** [gustavostz/whisper-clip#4]
Having an issue running this on my Macbook Pro.  Says ```ModuleNotFoundError: No module named 'winsound'```  from audio_recorder.py 

![Screenshot 2024-06-02 at 3 17 53 PM](https://github.com/gustavostz/whisper-clip/assets/81942023/aeac5dba-2605-488b-86ac-6189ae46d759)

**Comment by gustavostz** [comment]
@rachyrachyrach I made a change in the code, could you try again? :)

**Comment by gustavostz** [comment]
Closing the issue due to lack of response.

**Comment by rachyrachyrach** [comment]
Will try this out. Sorry, for some reason I didn’t receive an email that you replied.  Only email was the close.  I’ll try this out tomorrow.  Thank you for updating!

**Comment by rachyrachyrach** [comment]
It worked!  Thank you!
